# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-13 22:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields
import tastypie.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('language', models.CharField(max_length=4)),
                ('currency', models.CharField(max_length=3)),
                ('created', models.DateTimeField(default=tastypie.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('coordinates', jsonfield.fields.JSONField(default=dict)),
                ('bounding_rectangle', jsonfield.fields.JSONField(default=dict)),
                ('created', models.DateTimeField(default=tastypie.utils.timezone.now)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serviceareas.Provider')),
            ],
        ),
    ]
